### ISSUE TITLE
Is it possible to add vuetify components in a la carte in vue template component?

### ISSUE THREAD

**Issue by vinaybedre** [vuetifyjs/a-la-carte#4]
Instead of importing all necessary vuetify components in main.js, can we include in template component  eg App.vue 's script section?

**Comment by nekosaur** [comment]
I'm not sure I've tried this actually. I think you should be able to do

```
import VCard from 'vuetify/es5/components/VCard'

export default {
  components: { VCard }
}
```

If you do try it, please report back your result.

Also keep in mind that this repo is for the a-la-carte template, not the functionality itself. And any questions should be directed to the [chat](https://chat.vuetifyjs.com), as our issue boards are exclusively for bug reports and feature requests.

**Comment by maurop123** [comment]
Just this past week I used the a-la-carte functionality in that way, importing vuetify components inside child components and including them in the components property. Worked well for me.

**Comment by vinaybedre** [comment]
Hi,

It worked. But there is a glitch,
Eg.
```
<template>
<v-card>
        <v-card-media src="/static/doc-images/cards/desert.jpg" height="200px">
        </v-card-media>
        <v-card-title primary-title>
          <div>
            <h3 class="headline mb-0">Kangaroo Valley Safari</h3>
            <div>Located two hours south of Sydney in the <br>Southern Highlands of New South Wales, ...</div>
          </div>
        </v-card-title>
        <v-card-actions>
          <v-btn flat color="orange">Share</v-btn>
          <v-btn flat color="orange">Explore</v-btn>
        </v-card-actions>
      </v-card>
</template>
<script>
import VCard from 'vuetify/es5/components/VCard'
export default {
  components: {
    BelowFold,
    VCard
  }
}
</script>
```

Above code will work partially and result in error, as v-card-media is not yet registered, although VCard component has VCardMedia.

But by importing VCardMedia separately will work. I am not sure if this should be a question or bug. 
Reason: VCard's index.js already imports VCardMedia

**Comment by vinaybedre** [comment]
```
<template>
    <v-toolbar color="indigo" dark fixed app>
      <v-toolbar-title style="width: 300px" class="ml-0 pl-3">Veutify</v-toolbar-title>
     </v-toolbar>
</template>
<script>
import VToolbar from 'vuetify/es5/components/VToolbar'; //works
import VToolbarTitle from 'vuetify/es5/components/VCard/VCardTitle'; //does'nt work, as VCardTitle is not being exposed in seperate file
</script>
```

1 more example, where it doesn't work

**Comment by nekosaur** [comment]
Closing in favor of https://github.com/vuetifyjs/vuetify/issues/2472
