### ISSUE TITLE
Fails to start with Vuetify 1.0.2

### ISSUE THREAD

**Issue by JoseGoncalves** [vuetifyjs/a-la-carte#6]
This template fails to start up with Vuetify 1.0.2.
I get in the browser console:
![screenshot from 2018-02-21 09-34-35](https://user-images.githubusercontent.com/3037740/36472738-95e340ba-16ea-11e8-94b8-037e1050ce9a.png)

**Comment by nekosaur** [comment]
Fixed in 1.0.3
